# Generated by Django 3.0.4 on 2020-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Age', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
